const express = require('express')
const router = express.Router('')
const usercontroller = require('../controller/user')

// router.get('/home',usercontroller.home)
router.get('/shop',usercontroller.shop)
router.get('/about',usercontroller.about)
router.get('/contact',usercontroller.contact)  
router.get('/productdetail',usercontroller.productdetail)
router.get('/cartpage',usercontroller.cartpage)
router.get('/checkout',usercontroller.checkout)
router.get('contact',usercontroller.contact)
router.get('/signup',usercontroller.signup)
router.get('/login',usercontroller.login)
module.exports = router